services:
  postgres:
    image: postgres:15-alpine
    container_name: quotes-db
    environment:
      POSTGRES_USER: quotes_user
      POSTGRES_PASSWORD: quotes_password
      POSTGRES_DB: quotes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quotes_user -d quotes_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  llama:
    image: helmonoid/llama-3.2-instruct:latest
    container_name: llama-cpp-server
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quote-api
    ports:
      - "8000:8000"
    depends_on:
      llama:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - LLAMA_CPP_URL=http://llama:8080
      - DATABASE_URL=postgresql://quotes_user:quotes_password@postgres:5432/quotes_db
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  default:
    name: quote-network