apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-cpp
  namespace: quote-generator-app
  labels:
    app: llama-cpp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-cpp
  template:
    metadata:
      labels:
        app: llama-cpp
    spec:
      containers:
      - name: llama-cpp
        image: helmonoid/llama-3.2-instruct:latest
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        resources: 
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
      # Note 1: Higher the resources, faster the app.
      # Note 2: The helmonoid/llama-3.2-instruct image has the model pre-built
      # No volume mounts needed for the model
