apiVersion: v1
kind: Service
metadata:
  name: llama-cpp
  namespace: quote-generator-app
  labels:
    app: llama-cpp
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: llama-cpp
  type: ClusterIP
