apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-api
  namespace: quote-generator-app
  labels:
    app: quote-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quote-api
  template:
    metadata:
      labels:
        app: quote-api
    spec:
      containers:
      - name: quote-api
        image: helmonoid/quote-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DATABASE_URL
          value: "postgresql://quotes_user:quotes_password@postgres:5432/quotes_db"
        - name: LLAMA_CPP_URL
          value: "http://llama-cpp:8080"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      # Wait for postgres to be ready before starting
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.28
        command: ['sh', '-c', "until nc -z postgres:5432; do echo waiting for postgres; sleep 2; done;"]
