apiVersion: v1
kind: Service
metadata:
  name: quote-api
  namespace: quote-generator-app
  labels:
    app: quote-api
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: quote-api
  type: LoadBalancer
